### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by kostia1359** [kostia1359/homepage#5]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by witcher1359** [comment]
<h2>Résumé</h2>
<p>&mdash; Hello! I'm the most handsome <strong style="margin-left: 0.0625em;">*</strong>all over the world. I have had
    so many relationships, I don't remember all their names. I strive to kill monsters and help others. Unfortunately, I
    can not choose smaller evil </p>
<p style="opacity: 0.75;"><strong style="margin-right: 0.0625em;">*</strong>Except of Lambert of course</p>
