### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by kostia1359** [kostia1359/homepage#6]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by witcher1359** [comment]
<section>
    <h3>Languages</h3>
    <p class="tags small"><a href="#" rel="alternate" class="language" hreflang="el" lang="el">EL<span>ELVEN</span></a>
        <a href="#" rel="alternate" class="language" hreflang="ni" lang="ni">NI
            <span>Nilfgaardian</span></a> <span class="language" lang="en">&#x1f1fa;&#x1f1f8; ENGLISH</span>
    </p>
</section>
<section>
    <h3>Skills</h3>
    <p class="tags small"><span class="nowrap">Killing monsters</span> <span class="nowrap">Creating poisons</span>
        Hunting Treatment Teaching </p>
</section>
<section>
    <h3>Likes&#x1f603;</h3>
    <p class="tags small">Coin <span class="nowrap">One more coin</span> Humour Yennefer Triss Beer Speaking</p>
</section>
<section>
    <h3>Dislikes&#x1f61e;</h3>
    <p class="tags small"><span class="nowrap">Choosing smaller evil</span></p>
</section>
<section>
    <h3>Wants&#x1f97a;</h3>
    <p class="tags small"><span class="nowrap">Restful life</span> <span class="nowrap">A new horse</span> <span
            class="nowrap">Find Ciri</span></p>
</section>
<section>
    <h3>Best Quote</h3>
    <p class="tags small">We Have To Cling To Something. If We Don't, The World Descends Into Chaos.</p>
</section>
<section>
    <h3>You can see me here</h3>
    <p class="tags small bulleted">
        <span class="tag"><a href="https://store.steampowered.com/app/20900/The_Witcher_Enhanced_Edition_Directors_Cut/" rel="external"><strong>The Witcher: Enhanced Edition</strong></a></span>
        <span class="tag"><a href="https://store.steampowered.com/app/20920/The_Witcher_2_Assassins_of_Kings_Enhanced_Edition/" rel="external"><strong>The Witcher 2: Assassins of Kings</strong></a></span>
        <span class="tag"><a href="https://store.steampowered.com/app/292030/The_Witcher_3_Wild_Hunt/" rel="external"><strong>The Witcher® 3: Wild Hunt</strong></a></span>
        <span class="tag"><a href="https://www.netflix.com/fi-en/title/80189685" rel="external"><strong>The Witcher on Netflix</strong></a></span>
    </p>
</section>
