### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by kostia1359** [kostia1359/homepage#7]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by witcher1359** [comment]
<section>
    <h3>Experience</h3>
    <h6>Recent</h6>
    <ul class="timeline">
        <li class="highlighted">
            <p>
                <em>The Lady of the Lake</em>
            </p>
            <p>
                <strong>The story goes on, the story never ends</strong>
            </p>
        </li>
    </ul>
    <h6>Back then</h6>
    <ul class="timeline">
        
        <li>
            <p>
                <em>The Tower of the Swallow</em>
            </p>
            <p>
                <strong>I am looking for Ciri</strong>
            </p>
            <ol class="inverted">
                <li>
                    <p>Travelling with party</p>
                    <ul>
                        <li class="details">
                            <input type="checkbox" id="project-1">
                            <label for="project-1" class="summary">
                                Knight of Queen Meve
                            </label>
                            <div class="labels">
                                <span class="label">Nobel</span>
                                <span class="label">Wealth</span>
                                <span class="label">Famous</span>
                                <span class="label">prophecy</span>
                            </div>
                        </li>
                        <li>During our journey, we learn that a bounty has been placed on our heads by a
                            mysterious half-elf and a group of criminals led by a man named Nightingale.
                        </li>
                        <li>
                            I meet with an elven sage known as Avallac'h, who talk to me about Ithlinne's prophecy of
                            the end of the world, and how I must not seek out Ciri and that my search makes no
                            sense because what is predestined will happen, whatever he does, and that it is not
                            necessary for me to continue searching for her because there is already another person
                            helping Ciri.
                        </li>
                    </ul>
                </li>
                <li>
                    <p>Someone tried to kill me. Again&#128532;</p>
                    <ul>
                        <li>I suspected Djikstra</li>
                        <li>I found, it was Vilgefortz and Schirru</li>
                    </ul>
                </li>
            </ol>
        </li>
        
        <li>
            <p>
                <em>Baptism of Fire</em>
            </p>
            <p>
                <strong>I am restoring strength</strong>
            </p>
            <ul>
                <li>I recover in Brokilon forest after the Thanedd incident and meet Milva</li>
                <li>We are preparing for our journey for finding Ciri</li>
                <li>Now we are travelling with Zoltan, Regis and Cahir</li>
                <li>We help Queen Meve</li>
            </ul>
        </li>
        
        <li>
            <p>
                <em>Time of Contempt</em>
            </p>
            <p>
                <strong>I am spending time with my lovely</strong>
            </p>
            <ul>
                <li>Ciri helps me to meet Yennefer</li>
                <li>I visit reception with Yennefer</li>
                <li>Vilgefortz offers me to betray magician. I think, I would refuse</li>
                <li>I fight with Vilgefortz</li>
            </ul>
        </li>
        
        <li>
            <p>
                <em>Blood of Elves</em>
            </p>
            <p>
                <strong>I want Ciri to be alive</strong>
            </p>
            <ul>
                <li>I deliver Ciri to the Temple School in Ellander</li>
                <li>I want to track and kill Rience</li>
                <li>I am gravely wounded in the fight with Rience</li>
            </ul>
        </li>
        
        <li>
            <p>
                <em>Sword of Destiny</em>
            </p>
            <p>
                <strong>I know that Ciri belongs to me</strong>
            </p>
            <ul>
                <li>I visited Brokilon and I had known prophecy about Ciri</li>
                <li>I spend Beltane with Yennefer. It is really amazing</li>
                <li>Finally I meet Ciri, that was running from her enemies</li>
            </ul>
        </li>
        
        <li>
            <p>
                <em>The Last Wish</em>
            </p>
            <p>
                <strong>Who am I? None of your business, is </strong>
            </p>
            <ul>
                <li>Dandelion open the vase with a genie</li>
                <li>I visit Rinde to help my friend</li>
                <li>I was enchanted by Yennefer</li>
                <li>I am in the prison because of Yennefer</li>
                <li>I helped Yennefer to fight a genie and make my last wish</li>
            </ul>
        </li>
    </ul>
</section>
